node {
    stage("Git clone") {
        git branch: 'add-project', url: 'https://github.com/adarshnarayanhegde/ITFlex.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t adhegde/itflex-add-project /var/lib/jenkins/workspace/AddProjects/add-project/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u adhegde -p ${DockerPassword}"
        }
        sh "docker push adhegde/itflex-add-project"
    }

    stage('Redeploy Kubernetes') {
          sh '''
          ssh -i ~/itflex.pem ubuntu@149.165.171.174  " rm -rf ~/ITFlex &&
          git clone --single-branch --branch dev https://github.com/adarshnarayanhegde/ITFlex.git &&
          cd ~/ITFlex/Kubernetes/add-projects &&
          kubectl delete service add-project &&
          kubectl delete deployment add-project &&
          kubectl apply -f ."
          '''
      }
}
