node {
    stage("Git clone") {
        git branch: 'user-management', url: 'https://github.com/adarshnarayanhegde/ITFlex.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t adhegde/itflex-user-management /var/lib/jenkins/workspace/UserManagement/user-management/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u adhegde -p ${DockerPassword}"
        }
        sh "docker push adhegde/itflex-user-management"
    }

    stage('Redeploy Kubernetes') {
          sh '''
          ssh -i ~/itflex.pem ubuntu@149.165.171.174  " rm -rf ~/ITFlex &&
          git clone --single-branch --branch dev https://github.com/adarshnarayanhegde/ITFlex.git &&
          cd ~/ITFlex/Kubernetes/user-managemnt &&
          kubectl delete service user-managemnt &&
          kubectl delete deployment user-managemnt &&
          kubectl apply -f ."
          '''
      }

}
