node {
    stage("Git clone") {
        git branch: 'api-gateway', url: 'https://github.com/adarshnarayanhegde/ITFlex.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t adhegde/api-gateway /var/lib/jenkins/workspace/APIGateway/api-gateway/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u adhegde -p ${DockerPassword}"
        }
        sh "docker push adhegde/api-gateway"
    }

    stage('Redeploy Kubernetes') {
          sh '''
          ssh -i ~/itflex.pem ubuntu@149.165.171.174  " rm -rf ~/ITFlex &&
          git clone --single-branch --branch dev https://github.com/adarshnarayanhegde/ITFlex.git &&
          cd ~/ITFlex/Kubernetes/api-gateway &&
          kubectl delete service api-gateway &&
          kubectl delete deployment api-gateway &&
          kubectl apply -f ."
          '''
     }
}
