node {
    stage("Git clone") {
        git branch: 'search-filter', url: 'https://github.com/adarshnarayanhegde/ITFlex.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t adhegde/itflex-ui /var/lib/jenkins/workspace/SearchFilter/search-filter/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u adhegde -p ${DockerPassword}"
        }
        sh "docker push adhegde/itflex-ui"
    }
}
