node {
    stage("Git clone") {
        git branch: 'user-interface', url: 'https://github.com/adarshnarayanhegde/ITFlex.git'
    }

    stage("Build Docker Image") {
         sh "docker build -t adhegde/itflex-ui /var/lib/jenkins/workspace/UI/user-interface/"
    }

    stage("Docker image push") {
        withCredentials([string(credentialsId: 'DockerPassword', variable: 'DockerPassword')]) {
            sh "docker login -u adhegde -p ${DockerPassword}"
        }
        sh "docker push adhegde/itflex-ui"
    }

    stage('Redeploy Kubernetes') {
          sh '''
          ssh -i ~/itflex.pem ubuntu@149.165.171.174  " rm -rf ~/ITFlex &&
          git clone --single-branch --branch dev https://github.com/adarshnarayanhegde/ITFlex.git &&
          cd ~/ITFlex/Kubernetes/user-interface &&
          kubectl delete service user-interface &&
          kubectl delete deployment user-interface &&
          kubectl apply -f ."
          '''
      }
}
