apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-interface
  name: user-interfaceui
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: user-interface